sudo: false
addons:
  apt:
    packages:
    - git
language: groovy
jdk: oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.sonar/cache"
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
before_install:
- git fetch --unshallow || true
- git config user.email "rene.neubert@softcake.org"
- git config user.name "Travis-CI"
- git config url.https://.insteadOf git://
- git checkout -qf $TRAVIS_BRANCH
install:
- echo "skip default gradlew assemble"
script: travis_wait 30 "buildscripts/buildViaTravis.sh"

after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  matrix:
  - TERM=dumb
  global:
